server:
  port: 8080

spring:
  application:
    name: finsight

  datasource:
    url: ${LOCAL_POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

  ai:
    openai:
      api-key: ${AI_API_KEY}
      base-url: ${AI_BASE_URL}

      chat:
        options:
          model: ${AI_CHAT_MODEL}

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}
    refresh: ${JWT_SECRET_REFRESH}
